# Challenge 4
---
  - hosts: local
    become: true
    vars:
      names: [server1, server2, server3, server4]

    vars:
      server1: "{{ lookup('csvfile', 'server1 file=./variables/assignment_hosts.csv delimiter=, col=2') }} " 
      server2: "{{ lookup('csvfile', 'server2 file=./variables/assignment_hosts.csv delimiter=, col=2') }} " 
    
    vars_files:
      - ./variables/addresses.yml

    tasks:
      - name: loop to display the servername and address
        debug:
          msg: "{{ idx }}: {{ item }}"
        loop: "{{ addresses }}"
        loop_control:
          index_var: idx
      
      - name: log out the addresses of the two servers
        debug:
          msg:
            - "server1 : {{ server1 }}"
            - "server2 : {{ server2 }}"