# Registered Variables example
---
  - hosts: local
    vars:
      playbooks_location: "/home/jp/ansible/playbooks"
    tasks:
      - name: get the list of all playbooks conataining the word apache
        shell: ls {{ playbooks_location }} | grep apache
        register: playbooks_with_apache

      - name: list out all playbooks containing the word apache
        debug:
          msg: "{{ playbooks_with_apache }}"