# Registered Variables example
---
  - hosts: webservers
    vars:
      playbooks_location: "/var/www/github/ansible101/playbooks"
    tasks:
      - name: get the list of all playbooks conataining the word apache
        shell: ls {{ playbooks_location }} | grep -i apache
        register: playbooks_with_apache

      - name: list out all playbooks containing the word apache
        debug:
          msg: "{{ playbooks_with_apache }}"